import { z } from "zod";

import { completeRUTIfNeeded, isValidRUTFormat } from "@/lib/utils/rut";

export const rutSchema = z.string().min(1, "El RUT es requerido").refine((v) => /^(\d{1,2}\.?\d{3}\.?\d{3}-)[\dKk]$/.test(v), { message: "Formato de RUT inválido" }).refine((v) => { const c = v.replace(/\./g, "").replace(/-/g, ""); const r = c.slice(0, -1); const d = c.slice(-1).toUpperCase(); let s = 0; let m = 2; for (let i = r.length - 1; i >= 0; i--) { s += parseInt(r[i]) * m; m = m === 7 ? 2 : m + 1; } const e = 11 - (s % 11); const cd = e === 11 ? "0" : e === 10 ? "K" : e.toString(); return cd === d; }, { message: "RUT inválido" });
export const emailSchema = z.string().min(1, "El email es requerido").email("Email inválido");
export const phoneSchema = z.string().min(1, "El teléfono es requerido").refine((v) => /^(\+56\s?)?9\s?\d{4}\s?\d{4}$/.test(v.replace(/[-.]/g, " ")), { message: "Formato de teléfono inválido" }).optional();
export const nameSchema = z.string().min(1, "El nombre es requerido").min(2, "El nombre debe tener al menos 2 caracteres").max(100, "El nombre no puede exceder 100 caracteres").refine((v) => /^[a-zA-ZáéíóúÁÉÍÓÚñÑ\s'-]+$/.test(v), { message: "El nombre solo puede contener letras y espacios" });
export const priceSchema = z.string().min(1, "El precio es requerido").refine((v) => !isNaN(parseFloat(v)) && parseFloat(v) >= 0, { message: "El precio debe ser un número positivo" }).transform((v) => parseFloat(v));
export const quantitySchema = z.string().min(1, "La cantidad es requerida").refine((v) => !isNaN(parseInt(v)) && parseInt(v) > 0, { message: "La cantidad debe ser un número positivo" }).transform((v) => parseInt(v));
export const urlSchema = z.string().url("URL inválida").optional();
export const dateSchema = z.string().min(1, "La fecha es requerida").refine((v) => !isNaN(Date.parse(v)), { message: "Fecha inválida" });
export const postalCodeSchema = z.string().min(1, "El código postal es requerido").refine((v) => /^\d{7}$/.test(v), { message: "El código postal debe tener 7 dígitos" });
export const addressSchema = z.string().min(1, "La dirección es requerida").min(5, "La dirección debe tener al menos 5 caracteres").max(200, "La dirección no puede exceder 200 caracteres");
export const citySchema = z.string().min(1, "La ciudad es requerida").min(2, "La ciudad debe tener al menos 2 caracteres").max(100, "La ciudad no puede exceder 100 caracteres");
export const passwordSchema = z.string().min(8, "La contraseña debe tener al menos 8 caracteres").refine((v) => /[A-Z]/.test(v), { message: "Debe contener al menos una mayúscula" }).refine((v) => /[a-z]/.test(v), { message: "Debe contener al menos una minúscula" }).refine((v) => /\d/.test(v), { message: "Debe contener al menos un número" }).refine((v) => /[!@#$%^&*(),.?":{}|<>]/.test(v), { message: "Debe contener al menos un carácter especial" });
export const passwordConfirmationSchema = z.object({ password: passwordSchema, confirmPassword: z.string().min(1, "La confirmación es requerida") }).refine((data) => data.password === data.confirmPassword, { message: "Las contraseñas no coinciden", path: ["confirmPassword"] });

const optionalOrEmpty = <T extends z.ZodTypeAny>(schema: T) => z.union([z.literal(""), schema]).optional();
const optionalRutSchema = z.union([z.string(), z.undefined(), z.null()]).transform((v) => v == null || (typeof v === "string" && v.trim() === "") ? undefined : String(v).trim()).refine((v) => v === undefined || v === "" || isValidRUTFormat(completeRUTIfNeeded(v) || v), { message: "RUT inválido" });
const requiredPhoneSchema = z.string().min(1, "El teléfono es requerido").refine((v) => v.replace(/\D/g, "").length >= 8, { message: "Ingrese un número de contacto válido (mín. 8 dígitos)" });
const optionalPhoneSchema = z.string().optional().transform((v) => v === "" || v == null ? undefined : v).refine((v) => !v || v.trim() === "" || v.replace(/\D/g, "").length >= 8, { message: "Ingrese un número de contacto válido (mín. 8 dígitos)" });

export const customerSchema = z.object({ first_name: nameSchema, last_name: nameSchema, email: z.union([z.literal(""), z.string().email("Email inválido")]).optional().transform((v) => v === "" || v == null ? undefined : v), phone: requiredPhoneSchema, rut: optionalRutSchema, address_line_1: optionalOrEmpty(z.string().min(5).max(200)), address_line_2: z.string().max(200).optional().or(z.literal("")), city: optionalOrEmpty(z.string().min(2).max(100)), state: z.string().optional().or(z.literal("")), postal_code: z.string().max(20).optional().or(z.literal("")), country: z.string().default("Chile"), notes: z.string().max(500).optional().or(z.literal("")), branch_id: z.string().optional() });
export const customerEditSchema = z.object({ first_name: nameSchema, last_name: nameSchema, email: z.union([z.literal(""), z.string().email("Email inválido")]).optional().transform((v) => v === "" || v == null ? undefined : v), phone: optionalPhoneSchema, rut: optionalRutSchema, address_line_1: z.string().max(200).optional().or(z.literal("")), address_line_2: z.string().max(200).optional().or(z.literal("")), city: z.string().max(100).optional().or(z.literal("")), state: z.string().optional().or(z.literal("")), postal_code: z.string().max(20).optional().or(z.literal("")), country: z.string().default("Chile"), notes: z.string().max(500).optional().or(z.literal("")), branch_id: z.string().optional() });
export const productSchema = z.object({ name: z.string().min(1, "El nombre es requerido").max(200), slug: z.string().min(1, "El slug es requerido").regex(/^[a-z0-9-]+$/, "Solo letras minúsculas, números y guiones"), description: z.string().max(1000).optional(), price: priceSchema, sku: z.string().min(1).max(50), barcode: z.string().max(50).optional(), brand: z.string().max(100).optional(), category_id: z.string().min(1, "La categoría es requerida"), status: z.enum(["active", "draft", "archived"]) });
export const orderSchema = z.object({ customer_id: z.string().min(1), items: z.array(z.object({ product_id: z.string().min(1), quantity: quantitySchema, price: priceSchema })).min(1), shipping_address: addressSchema, shipping_city: citySchema, shipping_state: z.string().min(1), shipping_postal_code: postalCodeSchema, shipping_phone: phoneSchema, notes: z.string().max(500).optional() });
export const appointmentSchema = z.object({ customer_id: z.string().min(1), appointment_date: dateSchema, appointment_time: z.string().min(1), duration_minutes: z.number().min(15).max(180), appointment_type: z.enum(["examen", "entrega", "ajuste", "revisión", "otro"]), reason: z.string().min(1).max(200), notes: z.string().max(500).optional() });
export const prescriptionSchema = z.object({ customer_id: z.string().min(1), right_eye_sphere: z.string().optional(), right_eye_cylinder: z.string().optional(), right_eye_axis: z.string().optional(), right_eye_addition: z.string().optional(), left_eye_sphere: z.string().optional(), left_eye_cylinder: z.string().optional(), left_eye_axis: z.string().optional(), left_eye_addition: z.string().optional(), pd_far: z.string().optional(), pd_near: z.string().optional(), notes: z.string().max(500).optional() });
