export interface FormState {
  name: string;
  slug: string;
  short_description: string;
  description: string;
  price: string;
  price_includes_tax: boolean;
  category_id: string;
  featured_image: string;
  gallery: string[];
  stock_quantity: string;
  low_stock_threshold: string;
  is_featured: boolean;
  status: string;
  product_type: string;
  sku: string;
  barcode: string;
  brand: string;
  manufacturer: string;
  model_number: string;
  frame_type: string;
  frame_material: string;
  frame_shape: string;
  frame_color: string;
  frame_colors: string[];
  frame_brand: string;
  frame_model: string;
  frame_sku: string;
  frame_gender: string;
  frame_age_group: string;
  frame_size: string;
  frame_features: string[];
  frame_measurements: {
    lens_width: string;
    bridge_width: string;
    temple_length: string;
    lens_height: string;
    total_width: string;
  };
  lens_type: string;
  lens_material: string;
  lens_index: string;
  lens_coatings: string[];
  lens_tint_options: string[];
  uv_protection: string;
  blue_light_filter: boolean;
  blue_light_filter_percentage: string;
  photochromic: boolean;
  prescription_available: boolean;
  prescription_range: {
    sph_min: string;
    sph_max: string;
    cyl_min: string;
    cyl_max: string;
    add_min: string;
    add_max: string;
  };
  requires_prescription: boolean;
  is_customizable: boolean;
  warranty_months: string;
  warranty_details: string;
}

export const defaultFormState: FormState = {
  name: "",
  slug: "",
  short_description: "",
  description: "",
  price: "",
  price_includes_tax: false,
  category_id: "",
  featured_image: "",
  gallery: [],
  stock_quantity: "",
  low_stock_threshold: "5",
  is_featured: false,
  status: "active",
  product_type: "frame",
  sku: "",
  barcode: "",
  brand: "",
  manufacturer: "",
  model_number: "",
  frame_type: "",
  frame_material: "",
  frame_shape: "",
  frame_color: "",
  frame_colors: [],
  frame_brand: "",
  frame_model: "",
  frame_sku: "",
  frame_gender: "",
  frame_age_group: "",
  frame_size: "",
  frame_features: [],
  frame_measurements: {
    lens_width: "",
    bridge_width: "",
    temple_length: "",
    lens_height: "",
    total_width: "",
  },
  lens_type: "",
  lens_material: "",
  lens_index: "",
  lens_coatings: [],
  lens_tint_options: [],
  uv_protection: "",
  blue_light_filter: false,
  blue_light_filter_percentage: "",
  photochromic: false,
  prescription_available: false,
  prescription_range: {
    sph_min: "",
    sph_max: "",
    cyl_min: "",
    cyl_max: "",
    add_min: "",
    add_max: "",
  },
  requires_prescription: false,
  is_customizable: false,
  warranty_months: "",
  warranty_details: "",
};
